### PR TITLE
New features for scopes

### PR DESCRIPTION
**Pull request by CyberDeck**
This adds two new features:

1. Scopes can be defines using (constant) parameters:
If a model has defines a scope with parameters e.g.
`scope :has_lastname, ->(name) { where(last_name: name) }`
one can use an array of array for scopes to pass additional arguments like 
`autocomplete :user, :email, scopes: [[:has_lastname, 'MyScopeParam']]`

2. autocomplete can have an additional block to be evaluated during runtime:
Maybe one would like to filter the autocomplete result set with variables defines in a controller (think about a nested resource. One can define `autocomplete` with an additional block which is evaluated during runtime to further refine the result set:
`autocomplete(:user, :email) { |r| if @name then r.where(last_name: @name) else r end }`

Syntax is not really beautiful, at least it fits my needs. What is your opinion?

### CODE REVIEW

**Comment by tomichj** [comment]
This looks great at first glance! I'll read it more in depth and get back to you in the next 48 hours or so. Thanks!

**Comment by tomichj** [comment]
I like the functionality your change provides. 

I'm thinking about other ways to express `scopes: [[:has_lastname, 'MyScopeParam']]`, but I haven't come up with anything better.

**Comment by tomichj** [comment]
Thanks again for the contribution!

**Comment by CyberDeck** [comment]
Thank you for accepting my contribution. I banged my head to the wall to think about others way to express these types of scopes, but I finally could not find any other solution. Probably it is my lack of ruby skills.

**Comment by tomichj** [comment]
I'm work the problem a little bit more, but so far any solution that makes configuring 'scopes' more intuitive breaks the greater configuration paradigm of passing an options hash. I'm not terribly worried about it.

Thanks again!

**Pull request merged**
